pages/urls.py
from django.urls import path
from . import views
app_name = 'pages'

urlpatterns = [
    path('',views.Homepage.as_view(),name="homepage")
]

yumaf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models

# Create your models here.

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.


class Homepage(TemplateView):
    template_name = "index.html"

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="YUMAF is an authorized service provider in the field of Customs,
    Clearing, Freight Forwarding, We also advise on Transportation and
    Logistics">
    <meta name="keywords" content="Clearing, Forwading, Customs">

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/odometer.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/yumaf.css' %}">
    <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
    <title>YUMAF - Your Trusted Agent Of Choice</title>
</head>

<body>

    <div class="preloader">
        <div class="lds-ripple">
            <div></div>
            <div></div>
        </div>
    </div>


    <div class="prevoz-nav-style prevoz-nav-style-four fixed-top">
        <div class="navbar-area">

            <div class="mobile-nav">
                <a href="{% url 'pages:homepage' %}" class="logo">
                    <img src="{% static 'assets/img/logo/logo-01.png' %}" alt="Logo">
                </a>
            </div>

            <div class="main-nav">
                <nav class="navbar navbar-expand-md navbar-light">
                    <div class="container">
                        <a class="navbar-brand" href="{% url 'pages:homepage' %}">
                            <img src="{% static 'assets/img/logo/logo-02.png' %}" alt="Logo">
                        </a>
                        <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                            <ul class="navbar-nav m-auto">
                                <li class="nav-item"><a href="#home">Home</a></li>   
                                <li class="nav-item"><a href="#about">About Us</a></li>   
                                <li class="nav-item"><a href="#team">Team</a></li> 
                                <li class="nav-item"><a href="#service">Services</a></li> 
                                <li class="nav-item"><a href="#contact">Contact Us</a></li>   
                                
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>

    
    {% block content %}
        
    {% endblock content %}
        

    <footer class="footer-bottom-area footer-bottom-area-four">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="single-widget-bottom text-centerß">
                        <p>
                            Copyright <i class="bx bx-copyright"></i> {% now "Y" %} YUMAF.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <div class="go-top">
        <i class='bx bx-chevrons-up bx-fade-up'></i>
        <i class='bx bx-chevrons-up bx-fade-up'></i>
    </div>


    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/meanmenu.min.js' %}"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/appear.min.js' %}"></script>
    <script src="{% static 'assets/js/odometer.min.js' %}"></script>
    <script src="{% static 'assets/js/jarallax.min.js' %}"></script>
    <script src="{% static 'assets/js/ajaxchimp.min.js' %}"></script>
    <script src="{% static 'assets/js/form-validator.min.js' %}"></script>
    <script src="{% static 'assets/js/contact-form-script.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
</body>

</html>